kind: Template
apiVersion: v1
metadata:
  name: osd-monitor
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      service: osd-monitor
    name: osd-monitor
  spec:
    replicas: 1
    selector:
      service: osd-monitor
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          service: osd-monitor
      spec:
        serviceAccountName: osd-monitor
        volumes:
          - name: pcp-logs
            persistentVolumeClaim:
              claimName: osd-monitor-pcplogs
          - name: pcp-prom-endpoints
            configMap:
              name: osd-monitor-prom-endpoints
        containers:
        - image: '${IMAGE_PCP_CENTRAL_LOGGER}:${IMAGE_TAG}'
          name: pcp-central-logger
          volumeMounts:
            - name: pcp-logs
              mountPath: /var/log/pcp
          env:
            - name: ZABBIX_SERVER
              value: zabbix.devshift.net
            - name: VALGRIND
              value: ~
          resources:
            limits:
              cpu: 2000m
              memory: 3000Mi
            requests:
              cpu: 1m
              memory: 500Mi
        - image: '${IMAGE_PCP_PROMETHEUS_IN}:${IMAGE_TAG}'
          name: pcp-prometheus-in
          volumeMounts:
            - name: pcp-prom-endpoints
              mountPath: /var/lib/pcp/pmdas/prometheus/urls.d
          env:
            - name: PCP_HOSTNAME
              value: osio
            - name: PMCD_PORT
              value: "54320"
          ports:
            - containerPort: 54320
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 1m
              memory: 800Mi
        - image: '${IMAGE_PCP_CENTRAL_WEBAPI}:${IMAGE_TAG}'
          name: pcp-central-webapi
          volumeMounts:
            - name: pcp-logs
              mountPath: /var/log/pcp
          ports:
            - containerPort: 44323
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /pmapi/1/metrics?target=kernel.all.load
              port: 44323
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 8000m
              memory: 8000Mi
            requests:
              cpu: 1m
              memory: 500Mi
        - image: '${IMAGE_PCP_WEBAPI_GUARD}:${IMAGE_TAG}'
          name: pcp-webapi-guard
          env:
            - name: OAUTH2_PROXY_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: osd-monitor
                  key: redirect.url
            - name: OAUTH2_PROXY_GITHUB_ORG
              valueFrom:
                secretKeyRef:
                  name: osd-monitor
                  key: github.org
            - name: OAUTH2_PROXY_GITHUB_TEAM
              valueFrom:
                secretKeyRef:
                  name: osd-monitor
                  key: github.team
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: osd-monitor
                  key: client.id
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: osd-monitor
                  key: client.secret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: osd-monitor
                  key: cookie.secret
          ports:
            - containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: 8000
            periodSeconds: 60
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 200Mi
            requests:
              cpu: 1m
              memory: 50Mi
        - image: '${IMAGE_PCP_POSTGRESQL}:${IMAGE_TAG}'
          name: pcp-postgresql-f8tenant
          env:
            - name: PCP_HOSTNAME
              value: DB-f8tenant
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: f8tenant
                  key: postgres.host
            - name: DB_DB
              valueFrom:
                secretKeyRef:
                  name: f8tenant
                  key: postgres.database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: f8tenant
                  key: postgres.user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: f8tenant
                  key: postgres.password
            - name: PMCD_PORT
              value: "54321"
          ports:
            - containerPort: 54321
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 200Mi
            requests:
              cpu: 1m
              memory: 50Mi
        - image: '${IMAGE_PCP_POSTGRESQL}:${IMAGE_TAG}'
          name: pcp-postgresql-auth
          env:
            - name: PCP_HOSTNAME
              value: DB-auth
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: db.host
            - name: DB_DB
              value: postgres
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: db.user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: db.password
            - name: PMCD_PORT
              value: "54322"
          ports:
            - containerPort: 54322
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 200Mi
            requests:
              cpu: 1m
              memory: 50Mi
        - image: '${IMAGE_PCP_POSTGRESQL}:${IMAGE_TAG}'
          name: pcp-postgresql-core
          env:
            - name: PCP_HOSTNAME
              value: DB-f8core
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: core
                  key: db.host
            - name: DB_DB
              value: postgres
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: core
                  key: db.user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core
                  key: db.password
            - name: PMCD_PORT
              value: "54323"
          ports:
            - containerPort: 54323
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 200Mi
            requests:
              cpu: 1m
              memory: 50Mi
        - image: '${IMAGE_PCP_POSTGRESQL}:${IMAGE_TAG}'
          name: pcp-postgresql-jenkins-proxy
          env:
            - name: PCP_HOSTNAME
              value: DB-jenkins-proxy
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: jenkins-proxy
                  key: postgres.host
            - name: DB_DB
              valueFrom:
                secretKeyRef:
                  name: jenkins-proxy
                  key: postgres.database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: jenkins-proxy
                  key: postgres.user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jenkins-proxy
                  key: postgres.password
            - name: PMCD_PORT
              value: "54324"
          ports:
            - containerPort: 54324
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 200Mi
            requests:
              cpu: 1m
              memory: 50Mi
        - image: '${IMAGE_PCP_POSTGRESQL}:${IMAGE_TAG}'
          name: pcp-postgresql-f8cluster
          env:
            - name: PCP_HOSTNAME
              value: DB-f8cluster
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: f8cluster
                  key: db.host
            - name: DB_DB
              value: postgres
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: f8cluster
                  key: db.user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: f8cluster
                  key: db.password
            - name: PMCD_PORT
              value: "54325"
          ports:
            - containerPort: 54325
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 200Mi
            requests:
              cpu: 1m
              memory: 50Mi
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status:
    details:
      causes:
      - type: ConfigChange
- kind: Service
  apiVersion: v1
  metadata:
    name: osd-monitor
    labels:
      service: osd-monitor
  spec:
    ports:
      - name: 'osd-monitor-webapi-guard'
        protocol: TCP
        port: 80
        targetPort: 8000
    selector:
      service: osd-monitor
    type: ClusterIP
    sessionAffinity: None
- kind: Route
  apiVersion: v1
  metadata:
    name: osd-monitor
  spec:
    to:
      kind: Service
      name: osd-monitor
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: osd-monitor-prom-endpoints
  data:
    rhche_host.url: "http://rhche-host:8087/metrics\n"
- apiVersion: v1
  kind: ServiceAccount
  imagePullSecrets:
  - name: quay.io
  metadata:
    name: osd-monitor
parameters:
- name: IMAGE_PCP_CENTRAL_LOGGER
  value: quay.io/openshiftio/rhel-perf-pcp-central-logger
- name: IMAGE_PCP_CENTRAL_WEBAPI
  value: quay.io/openshiftio/rhel-perf-pcp-central-webapi
- name: IMAGE_PCP_PROMETHEUS_IN
  value: quay.io/openshiftio/rhel-perf-pcp-prometheus-in
- name: IMAGE_PCP_WEBAPI_GUARD
  value: quay.io/openshiftio/rhel-perf-pcp-webapi-guard
- name: IMAGE_PCP_POSTGRESQL
  value: quay.io/openshiftio/rhel-perf-pcp-postgresql-monitor
- name: IMAGE_OSO_CENTRAL_LOGGER
  value: quay.io/openshiftio/rhel-perf-oso-central-logger
- name: IMAGE_OSO_CENTRAL_WEBAPI_GUARD
  value: quay.io/openshiftio/rhel-perf-oso-central-webapi-guard
- name: IMAGE_TAG
  value: latest
