kind: Template
apiVersion: v1
metadata:
  name: osd-monitor
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      service: osd-monitor
    name: osd-monitor
  spec:
    replicas: 1
    selector:
      service: osd-monitor
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          service: osd-monitor
      spec:
        serviceAccountName: osd-monitor
        volumes:
          - name: pcp-logs
            persistentVolumeClaim:
              claimName: osd-monitor-pcplogs
        containers:
        - image: 'registry.devshift.net/perf/pcp-central-logger:${IMAGE_TAG}'
          name: pcp-central-logger
          volumeMounts:
            - name: pcp-logs
              mountPath: /var/log/pcp
          resources: {}
          env:
            - name: ZABBIX_SERVER
              value: zabbix.devshift.net
            - name: VALGRIND
              value: ~
        - image: 'registry.devshift.net/perf/pcp-central-webapi:${IMAGE_TAG}'
          name: pcp-central-webapi
          volumeMounts:
            - name: pcp-logs
              mountPath: /var/log/pcp
          ports:
            - containerPort: 44323
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /pmapi/1/metrics?target=kernel.all.load
              port: 44323
            initiaDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
        - image: 'registry.devshift.net/perf/pcp-webapi-guard:${IMAGE_TAG}'
          name: pcp-webapi-guard
          volumeMounts:
            - name: pcp-logs
              mountPath: /var/log/pcp
          ports:
            - containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /index.html
              port: 8000
            initiaDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
        - image: 'registry.devshift.net/perf/pcp-postgresql-monitor:${IMAGE_TAG}'
          name: pcp-postgresql-f8tenant
          env:
            - name: PCP_HOSTNAME
              value: DB-f8tenant
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: f8tenant
                  key: postgres.host
            - name: DB_DB
              valueFrom:
                secretKeyRef:
                  name: f8tenant
                  key: postgres.database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: f8tenant
                  key: postgres.user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: f8tenant
                  key: postgres.password
            - name: PMCD_PORT
              value: 54321
          ports:
            - containerPort: 54321
              protocol: TCP
        - image: 'registry.devshift.net/perf/pcp-postgresql-monitor:${IMAGE_TAG}'
          name: pcp-postgresql-auth
          env:
            - name: PCP_HOSTNAME
              value: DB-auth
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: db.host
            - name: DB_DB
              value: postgres
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: db.user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: db.password
            - name: PMCD_PORT
              value: 54322
          ports:
            - containerPort: 54322
              protocol: TCP
        - image: 'registry.devshift.net/perf/pcp-postgresql-monitor:${IMAGE_TAG}'
          name: pcp-postgresql-core
          env:
            - name: PCP_HOSTNAME
              value: DB-f8core
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: core
                  key: db.host
            - name: DB_DB
              value: postgres
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: core
                  key: db.user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core
                  key: db.password
            - name: PMCD_PORT
              value: 54323
          ports:
            - containerPort: 54323
              protocol: TCP
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status:
    details:
      causes:
      - type: ConfigChange
- kind: Service
  apiVersion: v1
  metadata:
    name: osd-monitor
    labels:
      service: osd-monitor
  spec:
    ports:
      - name: 'osd-monitor-webapi-guard'
        protocol: TCP
        port: 80
        targetPort: 8000
    selector:
      service: osd-monitor
    type: ClusterIP
    sessionAffinity: None
- kind: Route
  apiVersion: v1
  metadata:
    name: osd-monitor
  spec:
    to:
      kind: Service
      name: osd-monitor
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: osd-monitor
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      service: oso-monitor
    name: oso-monitor
  spec:
    replicas: 1
    selector:
      service: oso-monitor
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          service: oso-monitor
      spec:
        volumes:
          - name: pcp-logs
            persistentVolumeClaim:
              claimName: oso-monitor-pcplogs
          - name: oso-secrets
            secret:
              secretName: oso-monitor
              items:
              - key: oso.tenant.salt
                path: oso.tenant.salt
                mode: 292
        containers:
        - image: 'registry.devshift.net/perf/oso-central-logger:${IMAGE_TAG}'
          name: oso-central-logger
          volumeMounts:
            - name: pcp-logs
              mountPath: /var/log/pcp
            - name: oso-secrets
              mountPath: /run/secrets/oso-monitor
          resources: {}
          ports:
            - containerPort: 44321
              protocol: TCP
        - image: 'registry.devshift.net/perf/pcp-central-webapi:${IMAGE_TAG}'
          name: pcp-central-webapi
          volumeMounts:
            - name: pcp-logs
              mountPath: /var/log/pcp
          ports:
            - containerPort: 44323
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /pmapi/1/metrics?target=kernel.all.load
              port: 44323
            initiaDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
        - image: 'registry.devshift.net/perf/oso-central-webapi-guard:${IMAGE_TAG}'
          name: oso-central-webapi-guard
          volumeMounts:
            - name: pcp-logs
              mountPath: /var/log/pcp
          ports:
            - containerPort: 8001
              protocol: TCP
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status:
    details:
      causes:
      - type: ConfigChange
- kind: Service
  apiVersion: v1
  metadata:
    name: oso-monitor
    labels:
      service: oso-monitor
  spec:
    ports:
      - name: 'oso-monitor-webapi-guard'
        protocol: TCP
        port: 80
        targetPort: 8001
    selector:
      service: oso-monitor
    type: ClusterIP
    sessionAffinity: None
- kind: Route
  apiVersion: v1
  metadata:
    name: oso-monitor
  spec:
    to:
      kind: Service
      name: oso-monitor
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
parameters:
- name: IMAGE_TAG
  value: latest
